---
  - hosts: all
    name: server NFS mount check
    gather_facts: false
    become: true

# server NFS mount check
# NFS와 마운트 상태를 확인한 뒤, 
# mount 이상 유무에 따라 when 조건을 이용하여 msg를 나타낸다.

    tasks:
      - name: server NFS mount check
        shell: df -h | grep 'NFS'
        ignore_errors: yes
        register: bin

    #  - debug:
    #     var: bin.stdout_lines

      - name: NFS not mount
        debug:
         msg: "NFS mount is not set."
        when: bin is failed

      - name: NFS settings nomal
        debug:
         msg: "NFS mount settings are cool."
        when: bin is changed
