---
  - hosts: all
    name: no4.2 
    gather_facts: false
    become: true

    tasks:
      - name: /etc/rsyslog.conf << notice, alert
        lineinfile:
          path: /etc/rsyslog.conf
          line: |
           *.notice /var/log/messages
           *.alert /dev/console

      - name: ls -la
        shell: ls -la /etc/ | grep 'group$'
        register: group

      - debug:
         var: group.stdout_lines
