---
  - hosts: test
    name: root 계정 su 제한
    gather_facts: false
    become: true

    tasks:
      - name: pam_wheel 확인 
        shell: cat /etc/pam.d/su | grep 'wheel'
        ignore_errors: yes
        register: check

      - debug:
         var: check.stdout_lines

      - name: wheel 그룹 포함 유저 확인 
        shell: cat /etc/group | grep 'wheel'
        ignore_errors: yes
        register: group

      - debug:
         var: group.stdout_lines

