---
  - hosts: test
    name: 패스워드 정책 확인 
    gather_facts: false
    become: true

    tasks:
      - name: 패스워드 최소 길이 확인( 8자 이상 양호) 
        shell: cat /etc/login.defs | grep 'PASS_MIN_LEN'
        ignore_errors: no
        register: minlen

      - debug:
         var: minlen.stdout_lines

      - name: 패스워드 최대 사용기간 확인 ( 90일 이상 양호)
        shell: cat /etc/login.defs | grep 'PASS_MAX_DAYS'
        register: maxlen

      - debug: 
         var: maxlen.stdout_lines

      - name: 패스워드 최소 사용기간 확인 ( 1일(1주) 이상 양호) 
        shell: cat /etc/login.defs | grep 'PASS_MIN_DAYS'
        register: minday

      - debug:
         var: minday.stdout_lines

      - name: pam.d/passwd 기타 패스워드 설정 확인 
        shell: cat /etc/pam.d/passwd 
        register: pam_pw

      - debug:
         var: pam_pw.stdout_lines

