---
  - hosts: test
    name: passwd deny set
    gather_facts: false
    become: true

    tasks:
      - name: pam.d/system-auth check
        shell: cat /etc/pam.d/system-auth | grep 'pam_tally.so'
        ignore_errors: yes
        register: check

      - debug:
         var: check.stdout_lines


