---
  - hosts: all
    name: no2.12 PATH 환경변수 설정 확인 
    gather_facts: false
    become: true

    tasks:
      - name: PATH CHECK
        shell: |
          id 
          echo $PATH
        register: command_output


      - debug:
         var: command_output.stdout_lines

